apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vector-api-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: # optional: set your storage class, or omit to use default


